name:  NodeJs
on: 
  push:
     branches: master
jobs: 
  Build-Test: 
    runs-on:  ubuntu-latest
    steps: 
      - name:  Checkout Code
        uses:  actions/checkout@v4
        
      - name: Set up Nodejs
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          
      - name: Install Dependencies
        run: npm run install
          
      - name: Build
        run: npm run build
        
      - name: test
        run: npm run test
        
      - name: Artifact upload
        uses: actions/upload-artifact@v7
        with:
          name: artifact-1
          path: |
             package*

      - name: Deploy
        run: echo "code is deployed"
    
      
        
          
